# Generated by Django 4.2.30 on 2026-06-27 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_agent', models.CharField(max_length=120)),
                ('instruction_payload', models.TextField()),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('VERIFYING', 'Verifying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=32)),
                ('supervisor_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orchestration_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('original_prompt', models.TextField()),
                ('generated_diff', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspaces.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
