# Generated by hand for workspace storage foundation updates.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import re


def _normalize_username(raw: str) -> str:
    normalized = (raw or "").strip().lower()
    normalized = re.sub(r"[^a-z0-9_-]+", "-", normalized)
    normalized = re.sub(r"-+", "-", normalized).strip("-.")
    return normalized


def populate_project_owner_metadata(apps, schema_editor):
    Project = apps.get_model("workspaces", "Project")

    for project in Project.objects.select_related("locked_by").all():
        owner = getattr(project, "owner", None)
        if owner is None and project.locked_by_id:
            project.owner_id = project.locked_by_id

        username_source = ""
        if project.owner_id and getattr(project, "owner", None):
            username_source = project.owner.username
        elif project.locked_by_id and getattr(project, "locked_by", None):
            username_source = project.locked_by.username

        normalized_username = _normalize_username(username_source)
        if not normalized_username:
            normalized_username = f"legacy-project-{project.id}"

        project.path_owner_username = normalized_username
        project.save(update_fields=["owner", "path_owner_username", "updated_at"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0006_orchestrationrun_completion_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_projects", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="project",
            name="path_owner_username",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=120),
        ),
        migrations.RunPython(populate_project_owner_metadata, noop_reverse),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(fields=("path_owner_username", "name"), name="unique_project_name_per_path_owner"),
        ),
    ]
