# Generated by hand for orchestration observability foundation.

from django.db import migrations, models
import django.db.models.deletion


def backfill_approval_scope(apps, schema_editor):
    OrchestrationRun = apps.get_model("workspaces", "OrchestrationRun")
    TaskQueue = apps.get_model("workspaces", "TaskQueue")

    OrchestrationRun.objects.filter(status="PENDING_APPROVAL").update(approval_scope="LOCK")
    TaskQueue.objects.filter(status="PENDING_APPROVAL").update(approval_scope="LOCK")


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0007_project_storage_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orchestrationrun",
            name="approval_scope",
            field=models.CharField(choices=[("NONE", "No approval required"), ("LOCK", "Lock approval"), ("PLAN", "Plan approval")], default="NONE", max_length=16),
        ),
        migrations.AddField(
            model_name="taskqueue",
            name="approval_scope",
            field=models.CharField(choices=[("NONE", "No approval required"), ("LOCK", "Lock approval"), ("PLAN", "Plan approval")], default="NONE", max_length=16),
        ),
        migrations.CreateModel(
            name="OrchestrationRunActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=64)),
                ("level", models.CharField(choices=[("INFO", "Info"), ("WARNING", "Warning"), ("ERROR", "Error")], default="INFO", max_length=16)),
                ("session_id", models.CharField(blank=True, default="", max_length=255)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="workspaces.orchestrationrun")),
                ("step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="workspaces.orchestrationstep")),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="workspaces.taskqueue")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="OrchestrationArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("artifact_type", models.CharField(choices=[("PLAN", "Plan"), ("STEP_LIST", "Step list"), ("MESSAGE", "Message"), ("DIFF", "Diff"), ("SUPERVISOR_FEEDBACK", "Supervisor feedback"), ("SESSION_MESSAGES", "Session messages"), ("SESSION_DIFF", "Session diff"), ("SESSION_STATUS", "Session status"), ("SHELL_OUTPUT", "Shell output"), ("USAGE", "Usage"), ("ERROR", "Error"), ("APPROVAL", "Approval")], max_length=32)),
                ("session_id", models.CharField(blank=True, default="", max_length=255)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="workspaces.orchestrationrun")),
                ("step", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="workspaces.orchestrationstep")),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="workspaces.taskqueue")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.RunPython(backfill_approval_scope, noop_reverse),
    ]
