# Generated by hand for plan approval foundation.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0008_orchestration_observability_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="orchestrationrun",
            name="complexity_level",
            field=models.CharField(choices=[("SIMPLE", "Simple"), ("COMPLEX", "Complex")], default="SIMPLE", max_length=16),
        ),
        migrations.AddField(
            model_name="orchestrationrun",
            name="plan_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orchestrationrun",
            name="plan_requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OrchestrationPlanStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence_order", models.PositiveIntegerField(default=1)),
                ("assigned_agent", models.CharField(max_length=120)),
                ("instruction_payload", models.TextField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("APPROVED", "Approved"), ("REPLACED", "Replaced")], default="DRAFT", max_length=16)),
                ("planner_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="plan_steps", to="workspaces.orchestrationrun")),
            ],
            options={"ordering": ["sequence_order", "created_at"]},
        ),
        migrations.AlterField(
            model_name="orchestrationrun",
            name="status",
            field=models.CharField(choices=[("PENDING_APPROVAL", "Pending approval"), ("QUEUED", "Queued"), ("PLANNING", "Planning"), ("BREAKING_DOWN", "Breaking down"), ("PLAN_READY", "Plan ready"), ("AWAITING_PLAN_APPROVAL", "Awaiting plan approval"), ("RUNNING", "Running"), ("VERIFYING", "Verifying"), ("COMPLETED", "Completed"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], default="QUEUED", max_length=32),
        ),
    ]
