# Generated by Django 4.2.30 on 2026-06-29 17:46

from django.db import migrations, models


def seed_daemon_desired_state(apps, schema_editor):
    Project = apps.get_model('workspaces', 'Project')
    Project.objects.filter(daemon_pid__isnull=False).update(daemon_desired_state='RUNNING')


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_plan_approval_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daemon_desired_state',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('STOPPED', 'Stopped')], default='STOPPED', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='daemon_last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='daemon_stop_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(seed_daemon_desired_state, migrations.RunPython.noop),
    ]
