# Generated by Django 4.2.30 on 2026-06-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0010_project_daemon_desired_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationrun',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('', 'Not cancelled'), ('MANUAL_DAEMON_STOP', 'Manual daemon stop'), ('DAEMON_STOPPED', 'Daemon stopped'), ('DAEMON_CRASHED', 'Daemon crashed'), ('DAEMON_RESTART_FAILED', 'Daemon restart failed'), ('WORKER_CRASHED', 'Worker crashed'), ('RECOVERY_EXHAUSTED', 'Recovery exhausted')], default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='lock_acquired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
